# Generated by Django 4.1.5 on 2023-03-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_invitation_team_user_profile_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invitation',
            new_name='Invitations',
        ),
    ]
