# Generated by Django 4.1.5 on 2023-03-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_invitation_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rulebook', models.FileField(upload_to='rulebooks/')),
            ],
        ),
    ]
